# You Can Flip Any Election by Moving People Around: 2012

# Data Source

In [1]:
import pandas as pd

In [2]:
# data source: 2012 election results, wikipedia
url = "https://en.wikipedia.org/wiki/2012_United_States_presidential_election"

In [21]:
import requests

header = {
  "User-Agent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.75 Safari/537.36",
  "X-Requested-With": "XMLHttpRequest"
}

r = requests.get(url, headers=header)

tables = pd.read_html(r.text) # array of all dataframes

C:\Users\yasha\AppData\Local\Temp\ipykernel_20288\3458011634.py:10: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(r.text) # array of all dataframes

In [23]:
raw_df = tables[22]
raw_df.head()

  State or district Obama/Biden Democratic             Romney/Ryan Republican  \
  State or district                      #       %  EV                      #
0           Alabama                 795696  38.36%   –                1255925
1            Alaska                 122640  40.81%   –                 164676
2           Arizona                1025232  44.59%   –                1233654
3          Arkansas                 394409  36.88%   –                 647744
4        California                7854285  60.24%  55                4839958

              Johnson/Gray Libertarian            ... Stein/Honkala Green     \
        %  EV                        #      % EV  ...                   % EV
0  60.55%   9                    12328  0.59%  –  ...               0.16%  –
1  54.80%   3                     7392  2.46%  –  ...               0.97%  –
2  53.65%  11                    32100  1.39%  –  ...               0.34%  –
3  60.57%   6                    16276  1.52%  –  ...               0.87%  –
4  37.12%   –                   143221  1.10%  –  ...               0.66%  –

   Others              Margin          Margin Swing[a] Total votes  \
        #      % EV         #        %               % Total votes
0    6992  0.33%  –  −460,229  −22.19%          −0.61%     2074338
1    2870  0.96%  –   −42,036  −13.99%           7.55%      300495
2     452  0.02%  –  −208,422   −9.06%          −0.54%     2299254
3    1734  0.16%  –  −253,335  −23.69%          −3.84%     1069468
4  115445  0.88%  –   3014327   23.12%          −0.94%    13038547

  Unnamed: 20_level_0
  Unnamed: 20_level_1
0                  AL
1                  AK
2                  AZ
3                  AR
4                  CA

[5 rows x 21 columns]

# Data Transformation

In [ ]:
df = raw_df.copy(deep=True)

# remove the [] artifacts
import re

# Example column name
col = "State or district"
states = df[col][col]


# Remove square brackets and anything inside them
states = (
    states
    .str.replace(r"\[.*?\]", "", regex=True)          # remove [..]
    .str.replace(r"Tooltip.*", "", regex=True)        # remove Tooltip + following text
    .str.replace("†", "", regex=False)                # remove dagger symbol
    .str.strip()                                      # remove leading/trailing spaces
)


df.insert(1, "States", states)
df=df.drop("State or district", axis=1)

# remove unneeded columns, row, renamed for ease
df=df.drop(["Johnson/Gray Libertarian","Stein/Honkala Green","Others","Margin Swing[a]","Unnamed: 20_level_0"],level=0,axis=1)
df=df.drop(57)
# df = df.rename(columns={"Trump/Vance Republican": 'R', 'Harris/Walz Democratic': 'D'})
df

C:\Users\yasha\AppData\Local\Temp\ipykernel_20288\3610720906.py:22: PerformanceWarning: dropping on a non-lexsorted multi-index without a level parameter may impact performance.
  df=df.drop("State or district", axis=1)

                  States Obama/Biden Democratic               \
                                              #       %   EV
0                Alabama                 795696  38.36%    –
1                 Alaska                 122640  40.81%    –
2                Arizona                1025232  44.59%    –
3               Arkansas                 394409  36.88%    –
4             California                7854285  60.24%   55
5               Colorado                1323102  51.49%    9
6            Connecticut                 905083  58.06%    7
7               Delaware                 242584  58.61%    3
8   District of Columbia                 267070  90.91%    3
9                Florida                4237756  50.01%   29
10               Georgia                1773827  45.48%    –
11                Hawaii                 306658  70.55%    4
12                 Idaho                 212787  32.40%    –
13              Illinois                3019512  57.60%   20
14               Indiana                1152887  43.93%    –
15                  Iowa                 822544  51.99%    6
16                Kansas                 440726  37.99%    –
17              Kentucky                 679370  37.80%    –
18             Louisiana                 809141  40.58%    –
19                 Maine                 401306  56.27%    2
20                  ME-1                 223035  59.57%    1
21                  ME-2                 177998  52.94%    1
22              Maryland                1677844  61.97%   10
23         Massachusetts                1921290  60.65%   11
24              Michigan                2564569  54.21%   16
25             Minnesota                1546167  52.65%   10
26           Mississippi                 562949  43.79%    –
27              Missouri                1223796  44.38%    –
28               Montana                 201839  41.70%    –
29              Nebraska                 302081  38.03%    –
30                  NE-1                 108082  40.83%    –
31                  NE-2                 121889  45.70%    –
32                  NE-3                  72110  27.82%    –
33                Nevada                 531373  52.36%    6
34         New Hampshire                 369561  51.98%    4
35            New Jersey                2125101  58.38%   14
36            New Mexico                 415335  52.99%    5
37              New York                4485741  63.35%   29
38        North Carolina                2178391  48.35%    –
39          North Dakota                 124827  38.69%    –
40                  Ohio                2827709  50.67%   18
41              Oklahoma                 443547  33.23%    –
42                Oregon                 970488  54.24%    7
43          Pennsylvania                2990274  51.97%   20
44          Rhode Island                 279677  62.70%    4
45        South Carolina                 865941  44.09%    –
46          South Dakota                 145039  39.87%    –
47             Tennessee                 960709  39.08%    –
48                 Texas                3308124  41.38%    –
49                  Utah                 251813  24.75%    –
50               Vermont                 199239  66.57%    3
51              Virginia                1971820  51.16%   13
52            Washington                1755396  56.16%   12
53         West Virginia                 238269  35.54%    –
54             Wisconsin                1620985  52.83%   10
55               Wyoming                  69286  27.82%    –
56                 Total               65915795  51.06%  332

   Romney/Ryan Republican                   Margin          Total votes
                        #       %   EV           #        % Total votes
0                 1255925  60.55%    9    −460,229  −22.19%     2074338
1                  164676  54.80%    3     −42,036  −13.99%      300495
2                 1233654  53.65%   11    −208,422   −9.06%     2299254
3                  647744  60.57%    6    −253,335  −23.69%     1069468
4                 4839958  37.12%    –     3014327   23.12%    13038547
5                 1185243  46.13%    –      137858    5.36%     2569518
6                  634892  40.73%    –      270191   17.33%     1558960
7                  165484  39.98%    –       77100   18.63%      413921
8                   21381   7.28%    –      245689   83.63%      293764
9                 4163447  49.13%    –       74309    0.88%     8474179
10                2078688  53.30%   16    −304,861   −7.82%     3900050
11                 121015  27.84%    –      185643   42.71%      434697
12                 420911  64.09%    4    −208,124  −31.69%      656742
13                2135216  40.73%    –      884296   16.87%     5242014
14                1420543  54.13%   11    −267,656  −10.20%     2624534
15                 730617  46.18%    –       91927    5.81%     1582180
16                 692634  59.71%    6    −251,908  −21.72%     1159971
17                1087190  60.49%    8    −407,820  −22.69%     1797212
18                1152262  57.78%    8    −343,121  −17.20%     1994065
19                 292276  40.98%    –      109030   15.29%      713180
20                 142937  38.18%    –       80098   21.39%      374419
21                 149215  44.38%    –       28783    8.56%      336226
22                 971869  35.90%    –      705975   26.07%     2707327
23                1188314  37.51%    –      732976   23.14%     3167767
24                2115256  44.71%    –      449313    9.50%     4730961
25                1320225  44.96%    –      225942    7.69%     2936561
26                 710746  55.29%    6    −147,797  −11.50%     1285584
27                1482440  53.76%   10    −258,644   −9.38%     2757323
28                 267928  55.35%    3     −66,089  −13.65%      484048
29                 475064  59.80%    2    −172,983  −21.77%      794379
30                 152021  57.43%    1      -43949  -16.60%      264712
31                 140976  52.85%    1      -19087   -7.15%      266727
32                 182067  70.23%    1    −109,957  −42.41%      259223
33                 463567  45.68%    –       67806    6.68%     1014918
34                 329918  46.40%    –       39643    5.58%      710972
35                1477568  40.59%    –      647533   17.79%     3640292
36                 335788  42.84%    –       79547   10.15%      783758
37                2490431  35.17%    –     1995310   28.18%     7081159
38                2270395  50.39%   15     −92,004   −2.04%     4505372
39                 188163  58.32%    3     −63,336  −19.63%      322627
40                2661437  47.69%    –      166272    2.98%     5580847
41                 891325  66.77%    7    −447,778  −33.54%     1334872
42                 754175  42.15%    –      216313   12.09%     1789270
43                2680434  46.59%    –      309840    5.38%     5753670
44                 157204  35.24%    –      122473   27.46%      446049
45                1071645  54.56%    9    −205,704  −10.47%     1964118
46                 210610  57.89%    3     −65,571  −18.02%      363815
47                1462330  59.48%   11    −501,621  −20.40%     2458577
48                4569843  57.17%   38  −1,261,719  −15.79%     7993851
49                 740600  72.79%    6    −488,787  −48.04%     1017440
50                  92698  30.97%    –      106541   35.60%      299290
51                1822522  47.28%    –      149298    3.88%     3854489
52                1290670  41.29%    –      464726   14.87%     3125516
53                 417655  62.30%    5    −179,386  −26.76%      670438
54                1407966  45.89%    –      213019    6.94%     3068434
55                 170962  68.64%    3    −101,676  −40.82%      249061
56               60933504  47.20%  206     4982291    3.86%   129085410